export const categories = [
  { id: "shoes", name: "Giày Bóng Đá", icon: "👟", slug: "shoes" },
  { id: "jerseys", name: "Áo Đấu", icon: "👕", slug: "jerseys" },
  { id: "balls", name: "Bóng", icon: "⚽", slug: "balls" },
  { id: "accessories", name: "Phụ Kiện", icon: "🧤", slug: "accessories" },
  { id: "goalkeeper", name: "Thủ Môn", icon: "🧤", slug: "goalkeeper" },
  { id: "training", name: "Tập Luyện", icon: "🏋️", slug: "training" },
];

export const products = [
  {
    id: "1",
    name: "Nike Mercurial Vapor 16 Elite",
    slug: "nike-mercurial-vapor-16-elite",
    price: 4500000,
    salePrice: 3800000,
    brand: "Nike",
    category: "shoes",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    ],
    description: "Giày bóng đá đỉnh cao với công nghệ Flyknit siêu nhẹ, đế AG/FG phù hợp mọi mặt sân. Thiết kế aerodynamic giúp tăng tốc tối đa.",
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    colors: ["Đỏ/Đen", "Xanh/Trắng"],
    stock: 25,
    badge: "sale",
    rating: 4.8,
    reviews: 124,
    isActive: true,
    featured: true,
  },
  {
    id: "2",
    name: "Adidas Predator Elite",
    slug: "adidas-predator-elite",
    price: 5200000,
    salePrice: null,
    brand: "Adidas",
    category: "shoes",
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
    ],
    description: "Kiểm soát bóng vượt trội với các gai cao su Predstrike. Phù hợp cho tiền vệ và tiền đạo.",
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    colors: ["Đen/Vàng", "Trắng/Đỏ"],
    stock: 18,
    badge: "new",
    rating: 4.9,
    reviews: 89,
    isActive: true,
    featured: true,
  },
  {
    id: "3",
    name: "Áo Đấu Manchester City 2024/25 Home",
    slug: "ao-dau-man-city-2024-home",
    price: 1200000,
    salePrice: 950000,
    brand: "Puma",
    category: "jerseys",
    images: [
      "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&q=80",
    ],
    description: "Áo đấu chính thức Manchester City mùa 2024/25. Vải Drycell thoáng khí, thấm hút mồ hôi tốt.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Xanh Nhạt"],
    stock: 50,
    badge: "sale",
    rating: 4.7,
    reviews: 210,
    isActive: true,
    featured: true,
  },
  {
    id: "4",
    name: "Adidas Real Madrid 2024/25 Home",
    slug: "ao-dau-real-madrid-2024-home",
    price: 1350000,
    salePrice: null,
    brand: "Adidas",
    category: "jerseys",
    images: [
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=600&q=80",
    ],
    description: "Áo đấu Real Madrid chính hãng. Vải AEROREADY khô thoáng, in lụa chuẩn La Liga.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Trắng"],
    stock: 35,
    badge: "new",
    rating: 4.9,
    reviews: 178,
    isActive: true,
    featured: true,
  },
  {
    id: "5",
    name: "Nike Flight Premier League 2024",
    slug: "bong-nike-flight-premier-league",
    price: 2800000,
    salePrice: null,
    brand: "Nike",
    category: "balls",
    images: [
      "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&q=80",
    ],
    description: "Bóng thi đấu chính thức Premier League. Công nghệ AerowTrac Groove giúp kiểm soát quỹ đạo chuẩn xác.",
    sizes: ["Size 5"],
    colors: ["Trắng/Tím"],
    stock: 40,
    badge: null,
    rating: 4.6,
    reviews: 95,
    isActive: true,
    featured: false,
  },
  {
    id: "6",
    name: "Nike Tiempo Legend 10 Elite",
    slug: "nike-tiempo-legend-10-elite",
    price: 3900000,
    salePrice: 3200000,
    brand: "Nike",
    category: "shoes",
    images: [
      "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&q=80",
    ],
    description: "Da kangaroo tự nhiên mềm mại, đế FG bám sân cỏ tự nhiên. Lựa chọn của các tiền đạo cổ điển.",
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Đen/Vàng"],
    stock: 12,
    badge: "sale",
    rating: 4.7,
    reviews: 67,
    isActive: true,
    featured: false,
  },
  {
    id: "7",
    name: "Puma King Platinum Goalkeeper Gloves",
    slug: "puma-goalkeeper-gloves-platinum",
    price: 850000,
    salePrice: null,
    brand: "Puma",
    category: "goalkeeper",
    images: [
      "https://images.unsplash.com/photo-1565373677928-90e9e2a36bbd?w=600&q=80",
    ],
    description: "Găng tay thủ môn chuyên nghiệp. Lòng bàn tay Giga Grip bám cực tốt trong mọi điều kiện thời tiết.",
    sizes: ["8", "9", "10", "11"],
    colors: ["Đen/Vàng"],
    stock: 20,
    badge: null,
    rating: 4.5,
    reviews: 43,
    isActive: true,
    featured: false,
  },
  {
    id: "8",
    name: "Áo Đấu Barcelona 2024/25 Home",
    slug: "ao-dau-barcelona-2024-home",
    price: 1250000,
    salePrice: 999000,
    brand: "Nike",
    category: "jerseys",
    images: [
      "https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=600&q=80",
    ],
    description: "Áo đấu Barca chính hãng Nike. Thiết kế sọc đặc trưng, vải Dri-FIT ADV thoáng khí.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Đỏ"],
    stock: 28,
    badge: "sale",
    rating: 4.8,
    reviews: 156,
    isActive: true,
    featured: true,
  },
];

export const getProductById = (id) => products.find((p) => p.id === id);
export const getProductsByCategory = (category) =>
  products.filter((p) => p.category === category);
export const getFeaturedProducts = () => products.filter((p) => p.featured);

export const formatPrice = (price) =>
  new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(price);

export const getBadgeLabel = (badge) => {
  const map = { sale: "SALE", new: "MỚI", hot: "HOT" };
  return map[badge] || null;
};
